name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kirellkekw
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kirellkekw/test-image:${{ github.sha }}
